Écriture doc typerocket
Pixel-Circus/documentation pull request #12
Opened 2020-12-16 16:04 UTC by fredy31

2020-12-16 16:15 UTC, nebulousGirl requested changes
Ajouter un message de commit

2020-12-16 16:20 UTC, nebulousGirl commented
Est-ce que le fichier includes/typerocket-fields.php a tendance à devenir très long? Est-ce qu'il serait pertinent de proposer de le segmenter lorsqu'il devient trop long?

2020-12-16 16:20 UTC, nebulousGirl requested changes
Faire une révision du français.

2020-12-16 17:18 UTC, fredy31 commented
> Est-ce que le fichier includes/typerocket-fields.php a tendance à devenir très long? Est-ce qu'il serait pertinent de proposer de le segmenter lorsqu'il devient trop long?

Sa peut oui. Mais sauf des très gros sites, je crois pas sa nécessite de splitter tout dans de différents fichiers.

2020-12-16 20:00 UTC, nebulousGirl commented
> 
> 
> > Est-ce que le fichier includes/typerocket-fields.php a tendance à devenir très long? Est-ce qu'il serait pertinent de proposer de le segmenter lorsqu'il devient trop long?
> 
> Sa peut oui. Mais sauf des très gros sites, je crois pas sa nécessite de splitter tout dans de différents fichiers.

Ok, J'ai eu une idée en révisant BCA. On fait une fonction par bloc et on appelle la fonction dans le filtre. Ça donne un peu un principe de table des matières qui aiderait à la lisibilité d'un gros fichier.

2020-12-17 16:54 UTC, fredy31 commented
Mais un essai de la nouvelle méthode ici https://github.com/Pixel-Circus/BCA-SiteWordpress/commit/2c555adcf4541b00c958ae26df9dcf665d74ee18?branch=2c555adcf4541b00c958ae26df9dcf665d74ee18&diff=split

Essayé de l'expliquer, mais je sais pas, les mots me viennent pas.

2021-01-21 15:02 UTC, merged