Ajout de philosophies.
Pixel-Circus/documentation pull request #23
Opened 2021-01-22 20:09 UTC by fredy31

2021-01-27 13:30 UTC, nebulousGirl requested changes

2021-01-27 13:30 UTC, nebulousGirl commented on code/philosophie.md
> +L'interface de gestion du client devrait être la plus simple possible à gérer. Les éléments doivent être utilisés pour leur utilisation normale. Une page est une page, et n'est pas faite pour être un
Je ne comprends pas trop cette phrase. Généralement, lorsque je fais des admins. Je rends les options le plus génériques possibles pour que le concept puisse être réutilisé sur d'autres pages.

2021-01-27 20:35 UTC, fredy31 commented on code/philosophie.md
> +L'interface de gestion du client devrait être la plus simple possible à gérer. Les éléments doivent être utilisés pour leur utilisation normale. Une page est une page, et n'est pas faite pour être un
Je te dirais c'est plus que desfois, quand j'ai eu a reprendre des sites WP fait mal, je trouvais des affaires demême:

Il y a 3 vignettes pour les services, sans lien dessus pour voir la page. Mais l'intégrateur qui a fait sa a fait des sous page a la page en cours qui vont gérer ces 3 vignettes. La page est pareil visible dans le sitemap et tout sa, mais c'est une page morte puisque elle n'est pas faite pour être consultée, ever.

Jai la mentalité que cela sera lu par des nouveaux employés et en gros, faut les mettre straight avant qu'ils intègrent des sites... j'essaie de couvrir une erreur jai souvent vu quand jai ramassé des mauvais sites fait par quelqu'un d'autre.

J'imagine je pourrait ajouter, pour être plus clair, `toutte page créée dans le backend devrait être consultable`. Mais bon je vais me donner quelques jours voir comment je peux rework cette philosophie.

2021-03-09 21:35 UTC, fredy31 commented
@nebulousGirl simplement donné l'exemple a ne pas faire dans la doc, sa devrait expliquer ma pensée.

2021-03-10 21:05 UTC, nebulousGirl commented on code/philosophie.md
> +
Je pense que ça dépend de la situation. Si on veut stictement lier à des posts du site, on met un champ de relation, puis dans le post relié, on peut ajouter les champs additionnels. Par contre, si on veut pouvoir mettre un lien arbitraire, alors oui on met des champs custom dans le page d'accueil.

2021-03-18 18:29 UTC, merged