Ajout: Explication de comment fonctionne le webpack.
Pixel-Circus/documentation pull request #38
Opened 2021-01-25 21:04 UTC by fredy31

Fix #32

2021-01-27 13:43 UTC, nebulousGirl requested changes
Ça décrit plutôt npm que webpack. Il manque la documentation pour compiler webpack.

2021-01-27 20:40 UTC, fredy31 commented
C'est vrai. Même si je te dirais pour nous on modifie surtout NPM et Webpack fait ses propres choses (pour les nouveaux npm je saurais même pas ou aller pour ajouter du stuff au pipe, genre faire des versions Webp)

Alors est-ce que on renomme ma doc 'npm' et on fait une doc webpack a coté? Ou tandis que c'est intrisiquement relié on peut ajouter un peu de doc dans le meme fichier comment modifier webpack (chose qui va falloir que t'écrives, je sais pas trop par ou starter sa.)

2021-03-11 20:14 UTC, nebulousGirl approved these changes

2021-03-11 20:15 UTC, nebulousGirl commented
@fredy31 Je te laisse regarder ce que j'ai écrit.

2021-03-18 18:34 UTC, fredy31 reviewed
Sa ma l'air bon

2021-03-18 18:34 UTC, merged