Ecriture 8oct pm
Pixel-Circus/documentation pull request #5
Opened 2020-10-08 20:27 UTC by fredy31

2020-10-09 18:24 UTC, nebulousGirl commented on processus/mise-en-ligne.md
> +Récupérer la base de données live
@fredy31

2020-10-09 18:58 UTC, nebulousGirl requested changes
Petites corrections et commentaires

2020-10-09 18:58 UTC, nebulousGirl commented on outils/versionnement.md
> +Pour lorsque on ne travaille pas seul ou lorsqu'on travaille sur des fonctionalités aditionnelles/régler des bugs, à ce point il faut faire une branche pour chaque modification (ne pas aller a l'excè
Pour lorsqu'on ne travaille pas seul ou lorsqu'on travaille sur des fonctionalités additionnelles/régler des bugs, à ce point il faut faire une branche pour chaque modification (ne pas aller a l'excès, on s'entend, ne pas faire une branche pour une virgule...)

2020-10-09 18:58 UTC, nebulousGirl commented on code/react.md
> +- Axios, pour les requêtes de data a un json.
à un json

2020-10-09 18:58 UTC, nebulousGirl commented on code/react.md
> +- node-sass pour pouvoir import du sass dans des components React.
pouvoir importer du SASS

2020-10-09 18:58 UTC, nebulousGirl commented on outils/filezilla.md
> +Pour se conencter a un site que nous hébergeons, on a besoin d'une clé SSH.
Pour se connecter `s un site que nous hébergeons, on a besoin d'une clé SSH.

2020-10-09 18:58 UTC, nebulousGirl commented on outils/filezilla.md
> +- Aller sur le serveur (c05.cloud-cluster.org) et ajouter la clé (publique) sous SSH Access sur le compte du site. (Ne pas oublier de activer la clé SSH)
Ne pas oublier d'activer la clé SSH

2020-10-09 18:58 UTC, nebulousGirl commented on outils/visual-studio-code.md
> +Pas de configuration oligatoire.
Je mettrais ici les configurations recommandées qui sont utilisées par l'équipe

2020-10-09 18:58 UTC, nebulousGirl commented on processus/mise-en-ligne.md
> +Lors de la mise en ligne d'un site WP, quelques petites choses sont a ajouter.
à ajouter

2020-10-09 18:58 UTC, nebulousGirl commented on processus/mise-en-ligne.md
> +1. Installer Litespeed cache. Lier l'installation a un compte quic.cloud via le dashboard de Litespeed Cache.
à un compte

2020-10-09 19:37 UTC, fredy31 commented
Test commentaire

2020-10-14 17:28 UTC, nebulousGirl approved these changes

2020-10-14 17:29 UTC, merged