Passage au travers des liens pour retirer les liens morts et ajouter les pages qui n'étaient pas relié a quelque chose.
Pixel-Circus/documentation pull request #60
Opened 2021-04-06 17:39 UTC by fredy31

J'ai découvert un outil qui permet de faire du graphing de docs comme sa (je l'ai découvert en faisant de la recherche https://www.sitepoint.com/obsidian-beginner-guide/)

Jai essayé de plug la doc dedans, et sa a trouvé plein de liens qui allaient nulle part ou de pages qui n'étaient jamais reliées a la doc.

Avant:
![Screen Shot 2021-04-06 at 1 37 07 PM](https://user-images.githubusercontent.com/2183470/113754670-77fde980-96dd-11eb-8587-4125fdf92d49.png)

Après:
![Screen Shot 2021-04-06 at 1 35 17 PM](https://user-images.githubusercontent.com/2183470/113754700-7f24f780-96dd-11eb-9230-2108397a17fd.png)

2021-04-06 18:02 UTC, fredy31 commented
Fait un commit de plus pour mettre la table des matieres par page. Fait aussi un graph un peu plus lisible et trié dans obsidian,  pour que sa soit un peu plus clair (a voir si on garde l'architecture comme sa.)
![Screen Shot 2021-04-06 at 1 59 00 PM](https://user-images.githubusercontent.com/2183470/113757505-adf09d00-96e0-11eb-9d7c-c57242b17ae0.png)

2021-04-07 15:42 UTC, nebulousGirl requested changes
Ajouter une documentation sur ton outil et comment l'utiliser pour améliorer la doc.

2021-04-07 15:44 UTC, nebulousGirl commented
Bonne trouvaille.

2021-04-08 15:13 UTC, fredy31 commented
Ajout de docs pour Obsidian (et en meme temps jai fait une ptite doc Markdown)

2021-04-09 15:51 UTC, nebulousGirl approved these changes

2021-04-09 15:51 UTC, merged